
name: test
on:
  pull_request:
    branches: [dev, main]
  # push:
  #   branches: [dev, main]
jobs:
  build_and_test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "setup python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.9
          architecture: x64
      - name: Install Dep
        run: |
          python -m pip install pipenv
          python -m pipenv install
          python -m pipenv run black . --check